### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by agariaQ** [Tails2600/DDLC-NX#2]
The game does not start. Whether reinx or atmosphere it immediately crashes with a Lua error.

switch properties:
Switch version: 5.1
hbmenu version: 3.0.0
CFW: atmosphere 0.7.5/reinx 1.7.1
sdcard: 128gb exfat

DDLC-Log:
main.lua:24: bad argument #1 to 'setRandomSeed' (number expected, got nil)

Traceback

boot:238: in function <boot:225>
[C]: in function 'setRandomSeed'
./main.lua:24: in function <./main.lua:7>
[C]: in function 'xpcall'

Love Potion 1.1.0 (API 11.1.0)

Date and Time: Wed Dec 31 23:59:59 1969

A log has been saved to sdmc:/switch/log.txt

**Comment by Tails2600** [comment]
I don't know if you can change the date in your switches settings or not, but if you can try changing it to something else because it seems to be set to December 31, 1969.

**Comment by agariaQ** [comment]
I tried it but it didn't change in the log.

**Comment by Tails2600** [comment]
Try using this one.

https://www.dropbox.com/s/0leqywbftikfv67/DDLC-NX1.nro?dl=0

**Comment by agariaQ** [comment]
It works now. Thanks.
